export const CONSTANTS = {
  BASE_URL: "https://petstore.swagger.io/v2",
  COLORS: [
    "Blanco",
    "Negro",
    "Gris",
    "Cafe",
    "Marrón",
    "Rojo",
    "Amarillo",
    "Azul",
    "Verde",
    "Violeta",
    "Naranja",
    "Lila",
    "Rosa",
    "Marrón",
  ],
  TIPO: [
    "Perro",
    "Gato",
    "Hamster",
    "Conejo",
    "Cordero",
    "Pez",
    "Pulpo",
    "Tortuga",
    "Rana",
    "Cebra",
    "Tiburón",
    "Lobo",
    "Oveja",
    "Vaca",
    "Cerdo",
    "Canguro",
    "Araña",
    "Pez globo",
    "Cocodrilo",
    "Raton",
  ],
  RESIDENCIA: ["Soltero", "Pareja", "Familia"],
};
